"""https://in.images.search.yahoo.com/search/images;_ylt=AwrKB5ofaLJmxsUMLxK7HAx.;_ylu=Y29sbwNzZzMEcG9zAzEEdnRpZAMEc2VjA3BpdnM-?p=rohit+sharma&fr2=piv-web&type=E210IN826G0&fr=mcafee#id=3&iurl=https%3A%2F%2Fi1.wp.com%2Fshort-biography.com%2Fwp-content%2Fuploads%2Frohit-sharma%2FRohit-Sharma.jpg%3Fw%3D2000%26ssl%3D1&action=click

Revision ID: 9b9cb903298c
Revises: 
Create Date: 2024-08-06 23:45:46.845057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9cb903298c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('likes')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
